### ISSUE TITLE
Lock Portrait Mode

### ISSUE THREAD

**Issue by yalllah** [kit-recipe-app/front-end#81]

**Comment by bennybweng** [comment]
**Is your feature request related to a problem? Please describe.**
When users switch between portrait and landscape mode, the pages also turn with the phone. Since the app is only intended for use in portrait mode, some elements are not displayed correctly.

**Describe the solution you'd like**
Lock the app so it always stays in portrait mode, no matter how you turn the phone.


**Additional context**
Current behaviour when turning the phone to landscape mode:
![image](https://user-images.githubusercontent.com/93036165/220069072-3a255a68-4d80-4ea2-acfc-869156f9140d.png)
Expected behaviour:
![image](https://user-images.githubusercontent.com/93036165/220069232-cc099bd0-9e3c-4445-b22d-aa9636a8b384.png)
